language: c

env:
  global:
    - LUAROCKS=2.2.0beta1
  matrix:
    - LUA=lua5.1 ZMQ_VER=zeromq4
    - LUA=lua5.2 ZMQ_VER=zeromq4
    - LUA=luajit ZMQ_VER=zeromq4

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/setup_zmq.sh

install:
  - git clone https://github.com/moteus/lua-cmsgpack.git
  - cd lua-cmsgpack
  - git checkout add-streaming-and-refactor-and-tests
  - sudo luarocks make rockspec/lua-cmsgpack-scm-1.rockspec
  - cd $TRAVIS_BUILD_DIR
  - sudo luarocks install lua-llthreads2
  - if [ $LUA = "luajit" ]; then
      sudo luarocks install lzmq-ffi scm --server=http://rocks.moonscript.org/dev;
    else
      sudo luarocks install lzmq scm --server=http://rocks.moonscript.org/dev;
    fi
  - sudo luarocks make rockspecs/parallel-scm-0.rockspec

script: 
  - cd test 
  - lua$LUA_SFX test_basic_for.lua

notifications:
  email:
    on_success: change
    on_failure: always

